Add possibility to specify capability option value as an string
lmc-eu/steward pull request #115
Opened 2017-02-26 03:00 UTC by OndraM

Currently the data type of capability value given on CLI is smartly guessed:
- `--capability="platform:Linux"` => string `Linux`
- `--capability="foo:false"` => bool `false`
- `--capability="version:14.14393"` => float `14.14393`

However, in the last example, the version MUST be passed to selenium as an string (according to the WebDriver specification)m otherwise Selenium server throws an error: `Uncaught Facebook\WebDriver\Exception\UnknownServerException: java.lang.Double cannot be cast to java.lang.String`.

So now you can force the value to be casted to a string,  even if it looks like an number, by encapsulating it. All following should work and pass the version as an string:
- `--capability=version:'14.14393'`
- `--capability="version:'14.14393'"`
- `--capability=version:\"14.14393\"`
- `--capability="version:\"14.14393\""`

2017-02-28 21:35 UTC, jirinovak requested changes

2017-02-28 21:35 UTC, jirinovak commented on CHANGELOG.md
> +- Capabilities passed using `--capability` CLI option could now force to be be specified as an string (by encapsulating into additional quotes).
double `be`

2017-02-28 21:35 UTC, jirinovak commented on src-tests/Process/KeyValueCapabilityOptionsParserTest.php
> +     * @param string $expectedCapabilities
According to provider `capabilityOption` and `expectedCapabilities` should be arrays.

2017-02-28 21:35 UTC, jirinovak commented on src-tests/Process/KeyValueCapabilityOptionsParserTest.php
> +            'double enquoted string value should have the quoted removed' => [
`should have the quotes removed`?

2017-02-28 23:41 UTC, OndraM commented
@jirinovak Thanks, all fixed.

2017-03-01 09:11 UTC, jirinovak approved these changes

2017-03-01 13:26 UTC, merged